config/routes.rb
Unidler::Application.routes.draw do
  root 'pages#index'
  resources :sites, only: :create
  resources :pages, only: :index
end

app/models/site.rb
# == Schema Information
#
# Table name: sites
#
#  id              :integer          not null, primary key
#  address         :string(255)
#  name            :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  failure_counter :integer          default("0"), not null
#

class Site < ActiveRecord::Base
  validates :name, presence: true
  validates :address, presence: true, uniqueness: { case_sensitive: false, message: ' has already been added. No need to add it twice.'}
  validate :address_is_an_url
  
  before_validation :set_name

  FAILURE_THRESHOLD = 100

  def increase_failure_counter
    self.failure_counter += 1
  end

  def self.failures
    where("failure_counter > ?", FAILURE_THRESHOLD)
  end

  def self.addresses
    pluck(:address)
  end

  def self.reset_counters
    update_all(failure_counter: 0)
  end

  private

  def set_name
    self.name = self.address if self.name.blank?
  end

  def address_is_an_url
    begin
      http = Net::HTTP.new(self.address, 80)
      http.request_get('/')
    rescue SocketError => e
      errors.add(:address, ' entered is not valid. Please check the url again.')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @site = Site.new
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
  end

  def show
    @site = Site.find params[:id]
  end

  def new
    @site = Site.new
  end

  def create
    site = Site.new(site_params)
    if site.save
      SiteMailer.creation_notice(site.address).deliver
      flash[:notice] = "#{site.address} successfully added."
    else
      error = site.errors.full_messages.first || "#{site.address} cannot be added, please check the url again."
      flash[:error] = error
    end
    redirect_to root_path
  end

  def edit 
    @site = Site.find params[:id]
  end

  def update
    site = Site.find params[:id]
    site.update!(site_params)
    redirect_to root_path
  end

  private

  def site_params
    params.require(:site).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unidler</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <%= render 'shared/flash' %>
  <%= yield %>
  <%= render 'shared/ads' %>
  <%= render 'shared/footer' %>
  <%= render 'shared/addthis' %>
</body>
</html>

app/views/pages/index.html.haml
.container
  .jumbotron
    %h1
      Welcome to Unidler
    %p When you are using services like Heroku, your site usually goes idle in a couple of minutes to conserve resources. The unfortunate outcome is that the site will take a long time to become un-idle. This is where unidler comes in, it prevents your site from becoming idle, for a fast and reliable experience for your customers.
  =render 'sites/form', site: @site

app/views/shared/_addthis.html.haml
/ AddThis Smart Layers BEGIN
/ Go to http://www.addthis.com/get/smart-layers to customize
%script{src: "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-533ccdfb271c6b15", type: "text/javascript"}
:javascript
  addthis.layers({
    'theme' : 'transparent',
    'share' : {
      'position' : 'left',
      'numPreferredServices' : 3
    }   
  });
/ AddThis Smart Layers END

app/views/shared/_ads.html.haml
.container
  .pull-right
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- ok -->
    <ins class="adsbygoogle" data-ad-client="ca-pub-4554336371194565" data-ad-slot="3120439998"></ins>
    <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>

app/views/shared/_flash.html.haml
- flash.each do |name, msg|  
  %div{class: "alert alert-#{name == :notice ? "success" : "danger"}"}
    .container
      = msg

app/views/shared/_footer.html.haml
#footer
  Copyright &copy; Unidler. All Rights Reserved.

app/views/sites/_form.html.haml
=form_for site, html: { class: 'form-horizontal', role: 'form' } do |f|
  .form-group
    =f.label :address, "Enter your site's url and it's that easy!", class: 'col-sm-2 control-label'
    .col-sm-10
      =f.text_field :address, class: 'form-control', placeholder: 'url'
  .form-group
    .col-sm-offset-2.col-sm-10
      =f.submit 'Un-idle Site!', class: 'btn btn-primary btn-lg btn-block'

app/views/sites/edit.html.haml
%h3 Site Edit
=render 'form', site: @site

app/views/sites/index.html.haml
.container
  .jumbotron
    %h1
      Welcome to Unidler
    %p When you are using services like Heroku, your site usually goes idle in a couple of minutes to conserve resources. The unfortunate outcome is that the site will take a long time to become un-idle. This is where unidler comes in, it prevents your site from becoming idle, for a fast and reliable experience for your customers.
  =render 'form', site: Site.new 

app/views/sites/new.html.haml
%h3 Site New
=render 'form', site: @site

app/views/sites/show.html.haml
%h1=@site.name
=link_to 'index', sites_path
=link_to 'edit', edit_site_path(@site)

=@site.address